# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            code:
              - '.github/workflows/**'
              - 'main.go'
              - 'go.mod'
              - 'Dockerfile'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.filter.outputs.code == 'true'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.filter.outputs.code == 'true'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        if: steps.filter.outputs.code == 'true'
        with:
          username: rankun203
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        if: steps.filter.outputs.code == 'true'
        with:
          push: true
          tags: rankun203/go-file-server:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
